const decks = [
    {
        name: 'top_10',
        characters: [
        {char: '我', pinyin: 'wǒ', meaning: 'me'},
        {char: '你', pinyin: 'nǐ', meaning: 'you'},
        {char: '他', pinyin: 'tā', meaning: 'he'},
        {char: '她', pinyin: 'tā', meaning: 'she'},
        {char: '好', pinyin: 'hǎo', meaning: 'good'},
        {char: '是', pinyin: 'shì', meaning: 'to be'},
        {char: '的', pinyin: 'de', meaning: 'of'},
        {char: '了', pinyin: 'le', meaning: 'particle'},
        {char: '在', pinyin: 'zài', meaning: 'at'},
        {char: '有', pinyin: 'yǒu', meaning: 'to have'}
        ]
    },
    {
        name: 'top_50',
        characters: [
        {char: '人', pinyin: 'rén', meaning: 'person'},
        {char: '大', pinyin: 'dà', meaning: 'big'},
        {char: '小', pinyin: 'xiǎo', meaning: 'small'},
        {char: '中', pinyin: 'zhōng', meaning: 'middle'},
        {char: '国', pinyin: 'guó', meaning: 'country'},
        {char: '学', pinyin: 'xué', meaning: 'to study'},
        {char: '生', pinyin: 'shēng', meaning: 'life'},
        {char: '来', pinyin: 'lái', meaning: 'to come'},
        {char: '去', pinyin: 'qù', meaning: 'to go'},
        {char: '说', pinyin: 'shuō', meaning: 'to speak'},
        {char: '看', pinyin: 'kàn', meaning: 'to see'},
        {char: '听', pinyin: 'tīng', meaning: 'to listen'},
        {char: '吃', pinyin: 'chī', meaning: 'to eat'},
        {char: '喝', pinyin: 'hē', meaning: 'to drink'},
        {char: '走', pinyin: 'zǒu', meaning: 'to walk'},
        {char: '跑', pinyin: 'pǎo', meaning: 'to run'},
        {char: '坐', pinyin: 'zuò', meaning: 'to sit'},
        {char: '站', pinyin: 'zhàn', meaning: 'to stand'},
        {char: '睡', pinyin: 'shuì', meaning: 'to sleep'},
        {char: '起', pinyin: 'qǐ', meaning: 'to rise'},
        {char: '家', pinyin: 'jiā', meaning: 'home'},
        {char: '书', pinyin: 'shū', meaning: 'book'},
        {char: '水', pinyin: 'shuǐ', meaning: 'water'},
        {char: '火', pinyin: 'huǒ', meaning: 'fire'},
        {char: '天', pinyin: 'tiān', meaning: 'sky'},
        {char: '地', pinyin: 'dì', meaning: 'ground'},
        {char: '日', pinyin: 'rì', meaning: 'sun'},
        {char: '月', pinyin: 'yuè', meaning: 'moon'},
        {char: '年', pinyin: 'nián', meaning: 'year'},
        {char: '时', pinyin: 'shí', meaning: 'time'},
        {char: '分', pinyin: 'fēn', meaning: 'minute'},
        {char: '点', pinyin: 'diǎn', meaning: 'point'},
        {char: '多', pinyin: 'duō', meaning: 'many'},
        {char: '少', pinyin: 'shǎo', meaning: 'few'},
        {char: '新', pinyin: 'xīn', meaning: 'new'},
        {char: '老', pinyin: 'lǎo', meaning: 'old'},
        {char: '爱', pinyin: 'ài', meaning: 'love'},
        {char: '心', pinyin: 'xīn', meaning: 'heart'},
        {char: '想', pinyin: 'xiǎng', meaning: 'to think'},
        {char: '知', pinyin: 'zhī', meaning: 'to know'},
        {char: '道', pinyin: 'dào', meaning: 'way'},
        {char: '做', pinyin: 'zuò', meaning: 'to do'},
        {char: '工', pinyin: 'gōng', meaning: 'work'},
        {char: '作', pinyin: 'zuò', meaning: 'to make'},
        {char: '买', pinyin: 'mǎi', meaning: 'to buy'},
        {char: '卖', pinyin: 'mài', meaning: 'to sell'},
        {char: '钱', pinyin: 'qián', meaning: 'money'},
        {char: '开', pinyin: 'kāi', meaning: 'to open'},
        {char: '关', pinyin: 'guān', meaning: 'to close'},
        {char: '门', pinyin: 'mén', meaning: 'door'}
        ]
    }
];

